[package]
name = "tonks"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
shred = "0.9.3"
specs = "0.15.1"
crossbeam = "0.7.2"
hashbrown = "0.6.0"
parking_lot = "0.9.0"
smallvec = "0.6.10"
arrayvec = "0.5.0"