[package]
name = "tonks"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
shred = "0.9.3"
specs = "0.15.1"
crossbeam = "0.7.2"
hashbrown = "0.6.0"
rayon = "1.2.0"
parking_lot = "0.9.0"
smallvec = "0.6.10"
arrayvec = "0.5.0"
bumpalo = "2.6.0"
thread_local = "1.0.0"
bit-set = "0.5.1"
derivative = "1.0.3"

[features]
nightly = ["shred/nightly", "specs/nightly", "parking_lot/nightly"]

[dev-dependencies]
static_assertions = "1.0.0"
criterion = "0.3.0"

[[bench]]
name = "basic"
harness = false

[[bench]]
name = "oneshot"
harness = false
